[package]
name = "s3n"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "secure sourcing service network, s3n in rust"
    
[lints]
workspace = true

[dependencies]
s3n-aggregator.workspace = true
s3n-operator = {workspace = true , features = ["default"]}
s3n-cli-runner.workspace = true
s3n-config.workspace = true
s3n-avs.workspace = true
s3n-metrics.workspace = true
s3n-testing-utils.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
alloy.workspace = true
tracing.workspace = true
hex = "0.4.3"
metrics-exporter-prometheus = "0.15.3"
rust-bls-bn254.workspace = true
eigen-crypto-bls.workspace = true
metrics-util = "0.17.0"
# eigen-rs
eigen-testing-utils.workspace = true
eigen-logging.workspace = true
eigen-utils.workspace = true
eigen-client-avsregistry.workspace = true
eigen-client-elcontracts.workspace = true
eigen-types.workspace = true
eigen-metrics.workspace = true

[dev-dependencies]
tokio.workspace = true


[[bin]]
name = "s3n"
path = "src/main.rs"